[package]
name = "mikofia-deno"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
deno_core = "0.350"
deno_runtime = "0.215"
deno_ast = { version = "=0.51.0", features = ["transpiling"] }
globset = "0.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
mikofia = { path = "../mikofia" }
rand = "0.8"

[dev-dependencies]
tempfile = "3"
